export const defaultTag = [
  "Following",
  "Services",
  "Computers & Tech",
  "Mobile Phones & Gadgets", 
  "Women's Fashion", 
  "Property", 
  "Men's Fashion", 
  "Cars", 
  "Beauty & Personal Care", 
  "Luxury", 
  "Free Items", 
  "Video Gaming", 
  "Audio", 
  "Books",
  "Photography", 
  "Furniture & Home Living", 
  "TV & Home Appliances", 
  "Babies & Kids", 
  "Hobbies & Toys", 
  "Health & Nutrition",
  "Sports Equipment", 
  "Food & Drinks", 
  "Pet Supplies", 
  "Tickets & Vouchers", 
  "Motorbikes", 
  "Auto Accessories",
  "Jobs",
  "Community",
  "Preorders",
  "Looking For", 
  "Everything Else",
  "Announcements"
]

export const defaultStatus = [
  "ACTIVE", "HIDDEN", "ON_HOLD", "DEALING", "CLOSED"
]

export const tagObj = {
  Following:"Following",
  Services:"Services",
  Computers:"Computers & Tech",
  Mobile:"Mobile Phones & Gadgets",
  Women:"Women's Fashion",
  Property:"Property",
  Men:"Men's Fashion",
  Cars:"Cars",
  Beauty:"Beauty & Personal Care",
  Luxury:"Luxury",
  Free:"Free Items",
  Video:"Video Gaming",
  Audio:"Audio",
  Photography:"Photography",
  Furniture:"Furniture & Home Living",
  TV:"TV & Home Appliances",
  Babies:"Babies & Kids",
  Hobbies:"Hobbies & Toys",
  Health:"Health & Nutrition",
  Sports:"Sports Equipment",
  Food:"Food & Drinks",
  Pet:"Pet Supplies",
  Tickets:"Tickets & Vouchers",
  Motorbikes:"Motorbikes",
  Auto:"Auto Accessories",
  Jobs:"Jobs",
  Community :"Community",
  Preorders:"Preorders",
  Looking:"Looking For",
  Everything:"Everything Else",
  Announcements:"Announcements",
}